version: "3.9"

services:
  flask_app_api:
    container_name: api-flask
    image: api_flask_postgres:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@db_flask:5432/postgres
    depends_on:
      - db_flask

  db_flask:
    container_name: db_flask
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}